export const AWS_REGION_ENV = 'AWS_REGION';
export const AWS_S3_BUCKET_NAME_ENV = 'AWS_S3_BUCKET_NAME';
export const AWS_ACCESS_KEY_ID_ENV = 'AWS_ACCESS_KEY_ID';
export const AWS_SECRET_ACCESS_KEY_ENV = 'AWS_SECRET_ACCESS_KEY';
export const CLOUDFRONT_DOMAIN_ENV = 'CLOUDFRONT_DOMAIN';
export const CLOUDFRONT_KEY_PAIR_ID_ENV = 'CLOUDFRONT_KEY_PAIR_ID';
export const CLOUDFRONT_PRIVATE_KEY_ENV = 'CLOUDFRONT_PRIVATE_KEY';
export const CLOUDFRONT_SIGNED_URL_EXPIRES_SECONDS_ENV =
  'CLOUDFRONT_SIGNED_URL_EXPIRES_SECONDS';

export const DEFAULT_S3_CACHE_CONTROL = 'public, max-age=31536000, immutable';
export const DEFAULT_CLOUDFRONT_SIGNED_URL_EXPIRES_SECONDS = 60 * 5;
